### ISSUE TITLE
cookie是否完整？

### ISSUE THREAD

**Issue by lookinghong** [coldnight/tornadohttpclient#2]
- 把cookie保存到文件，再恢复，却不能成功访问？

- 如果用浏览器的cookie，是可以成功访问

**Comment by coldnight** [comment]
已尝试修复, 参见: https://github.com/coldnight/tornadohttpclient/commit/4de737ce6b646b362c8f310720b10cc373fc4c7c

**Comment by lookinghong** [comment]
Thx!

- 调用self.cookiejar之前必须先调用self.cookie，否则为空，是否合理？

- cookie的恢复操作，我先使用cookiejar生成cookie_str，保存到文件，然后用set_global_headers{'Cookie': cookie_str}，是否需要加个直接生成cookie_str的函数?

**Comment by coldnight** [comment]
> 调用self.cookiejar之前必须先调用self.cookie，否则为空，是否合理？

已修复: https://github.com/coldnight/tornadohttpclient/commit/ba542f9aaf78ef6675ebfc13738d010cdbb2948c

> cookie的恢复操作，我先使用cookiejar生成cookie_str，保存到文件，然后用 ...

抱歉, 由于目前没多少时间处理所以暂时不会考虑增加此类函数.
